### ISSUE TITLE
Проблема при выборе расписания по группе

### ISSUE THREAD

**Issue by vitta** [h4/spbstu-schedule#142]
Есть проблема с номером группы, передаваемом при выборе расписания.
1. Первый выбор - все ок
2. Если воспользоваться в браузере Back, и выбрать другую группу, то на странице показывается номер предыдущей, хотя в url подставился id нужной. После обновления расписание показывается правильно.
2. Если перейти на начальную страницу, и снова выбрать другую группу, все ок. 
Видео по ссылке, смотреть без звука, у нас тут колл-центр :)
https://drive.google.com/file/d/0B__xVXAFNZWXdm0tbTlDYWkxUE0/view?usp=sharing

**Comment by h4** [comment]
Исправлено. @ftomza надо бы раскатать новый релиз.

**Comment by ftomza** [comment]
Обновил! @h4 только вот gulp пришлось вызывать руками `./node_modules/gulp/bin/gulp.js`.

**Comment by h4** [comment]
@ftomza там же есть `npm run build` для этого.
