### ISSUE TITLE
Убрать список групп потока из расписания группы

### ISSUE THREAD

**Issue by vitta** [h4/spbstu-schedule#16]
Можно ли сделать так: 
- если зашли в расписание группы http://ruz.spbstu.ru/faculty/92/groups/19672  не показывать длинный список групп. Выглядит длинно-предлинно. 
- если зашли в расписание преподавателя http://ruz.spbstu.ru/teachers/29152 , то Группы показывать
- если зашли в расписание аудитории http://ruz.spbstu.ru/places/14/970, то Группы тоже показывать

**Comment by h4** [comment]
Да, можно.

**Comment by h4** [comment]
Сделал немного не так. Длинные списки потоков скрыты по дефолту, но их можно раскрывать.
