### ISSUE TITLE
Не генерируется index.js

### ISSUE THREAD

**Issue by ftomza** [h4/spbstu-schedule#164]
@shirofaii на ветке prod не собирается файл `src/index.js` после выполнения `./node_modules/gulp/bin/gulp.js`

**Comment by shirofaii** [comment]
единственный js файл который генерируется командой `npm build` это `src/asssets/bundle.js`. Файл index.js действительно отсутствует, сервер запускается через `npm start`. Но перед этим нужно не забыть про `npm install`, чтобы обновить и установить пакеты

**Comment by ftomza** [comment]
Тогда нужно решать куда делся index.js

**Comment by shirofaii** [comment]
он превратился в server.js

**Comment by ftomza** [comment]
Скрипты запуска исправлены, ветку накатил.
