### ISSUE TITLE
Не разворачиваются потоки по ссылке Показать группы в IE

### ISSUE THREAD

**Issue by vitta** [h4/spbstu-schedule#58]
Замечено в IE 11.
![image](https://cloud.githubusercontent.com/assets/2279586/11331392/34491c04-91cb-11e5-81d3-4765a530738d.png)

**Comment by h4** [comment]
В консоль пишет что-то при этом?

**Comment by vitta** [comment]
Ничего, связанного с щелчком по этой ссылке$, сразу при открытии ruz.spbstu.ru появляется вот такое:
![image](https://cloud.githubusercontent.com/assets/2279586/11331768/0adb407c-91d0-11e5-9c47-427bf7d0e98e.png)

**Comment by h4** [comment]
Ага, он просто валится, зараза. Из-за вот этого `Object.assign`.

**Comment by h4** [comment]
В общем, спасибо за репорт, буду разбираться, почему оно сломалось. Вроде как я уже делал нужные вещи для того, чтобы этого бага в IE не было.

**Comment by h4** [comment]
Проверил дома на виртуалке в IE11. Действительно, почему-то падает исключение. Более детально не копал.

PS. Как здорово, что я прикрутил серверный рендеринг и почти всё работает даже с неработающим JS.

**Comment by h4** [comment]
@vitta исправил. Проверяй.

**Comment by vitta** [comment]
Все работает! спасибо.
