### ISSUE TITLE
Сломался переход к след./пред. неделе в ИЕ. 

### ISSUE THREAD

**Issue by vitta** [h4/spbstu-schedule#60]
Параметр в урл подставляется, на странице расписание не меняется. 
![image](https://cloud.githubusercontent.com/assets/2279586/11417037/47c79912-9424-11e5-9340-480320ef8fc8.png)

**Comment by h4** [comment]
Таак, всё-таки не удалось избежать необходимости нормально разобраться с ES6.

**Comment by vitta** [comment]
Получится исправить?

**Comment by h4** [comment]
Да, там надо сесть сборку статики перепилить и всё починится.
